### ISSUE TITLE
[FEATURE] New question type - Ad

### ISSUE THREAD

**Issue by tm-opinodo** [Opinodo/opinodo-surveys#5]
### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like

We should add a new question type, "Ad," so the Editor/Admin can create a survey with an ad between questions. For now, it is enough to support Adsense ads only.

### Additional context

You can check how we insert Ads on Digiopinion end pages.

**Comment by tm-opinodo** [comment]
@rlopino I wanted your feedback/input on this.  What we know for sure that it has to have clearly visible buttons to move away from it. Have any other suggestion on design? 

![Image](https://github.com/Opinodo/opinodo-surveys/assets/90531267/3c43d8f5-60d9-44fc-8a1a-d246072bfe60)

**Comment by rlopino** [comment]
I guess the question is if it is better to not even have the option to add any text on that ad screen? So that it only had some sort of disclaimer. It needs to be easy to add an "ad question" in each survey. Of course if it is possible to simply leave the text blank, and it still looks nice, then problem solved. I probably need to think about it a bit more, or we can have a call tomorrow maybe, as I guess it is a quite important discussion. I just struggle to see what I would put as the text for an add if it was me.

**Comment by tm-opinodo** [comment]
That's true; we could have only a title saying _this is an Ad_. If we serve only a disclaimer, I don't think we even have to translate it - at least in the first version.

I was afraid that Google would mark it as a thin content page, but a sentence or two wouldn't help if that is the case. 

What do you think? Should we start with the disclaimer and buttons only and deal with potential problems only when/if Google Adsense notices them?

**Comment by rlopino** [comment]
Ah, didn't think about thin content, you are probably right. Let me look into it tomorrow. I might be in the office here with Niels T tomorrow - if he is there I will get his opinion,

**Comment by rlopino** [comment]
I talked to Niels, he suggested that maybe we have a small block of test below, so like you would have to scroll to see it. Here's is a liunk to a quick mockup, but I still need to also show Niels: https://www.canva.com/design/DAGC2Z2YFqI/ZJ-J_DaXQ9JI1prcHd2CSg/view?utm_content=DAGC2Z2YFqI&utm_campaign=designshare&utm_medium=link&utm_source=editor

**Comment by tm-opinodo** [comment]
Seems good, let's wait for NT approval, and we can start with it. 

Would you require this text to be translated?

**Comment by rlopino** [comment]
Ok, Niels approves this version. I don't know if we need a place in the settings where this text can be edited, or if this is just something you guys can put in. Just not sure if this is the "final" text. Niels says no translation needed, but we need something above the ad that says "Ad:" or "Advertisement:"

**Comment by tm-opinodo** [comment]
Yes, we use  _Sponsored links_  title everywhere where we place ads. 

So, let's have a question-type Ad with a Sponsored links title, an Ad, navigation buttons, and text below it. We will start with the text you gave us already but feel free to send us a new "version" of it whenever.

Nothing is configurable by the Editor (User that creates surveys in surveys.digi). Editor can only choose between which questions he wants an Ad.

Does it make sense?

**Comment by rlopino** [comment]
Yes yes, as long as we can change it at one point, this was just somethign I quickly wrote, but its ok for now.

**Comment by tm-opinodo** [comment]
Just confirmed by Klintoe - we should use the ads script from member.digiopinion (with same params)

**Comment by rlopino** [comment]
Hi guys, are there any updates on this one? Let me know if there is something to show or something to discuss.

**Comment by tm-opinodo** [comment]
Hey Rasmus, yep this is in progress, should be shipped next week.
