### ISSUE TITLE
[FEATURE] Update branding

### ISSUE THREAD

**Issue by tm-opinodo** [Opinodo/opinodo-surveys#6]
### Is your feature request related to a problem? Please describe.

Nope

### Describe the solution you'd like

Since we are paying for enterpirse edition we are allowed to rebrand Formbricks to Digiopinion Surveys.
All links that surveying user can see leading to formbricks.com should be changed to member.digiopinion.com.
Logo should be update to be digiopinion. 

You can use this [logo](https://member.digiopinion.com/img/thick_logo.svg), also you can use only bird logo for wherever needed. 

Also, update branding in emails - change from Name and logos.

**Comment by mmopinodo** [comment]
![image](https://github.com/Opinodo/opinodo-surveys/assets/157482619/fa2c76c0-bc3b-4bf5-9bc9-f1c31c409bc7)
just to leave this here for now, can be answered later. 

this button can either be removed or kept. currently, I just put this "join digiopinion" text and link to digi, but I'm not sure how much sense that makes sense when the users come to the page from digiopinion.
